version: '3.1'
services:
  myfirstapp:
    image: 'demo101dc'
    build: 
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Logging__LogLevel__Default=Warning

  mysecondapp:
    image: 'demo101dc'
    build: 
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "9090:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - Logging__LogLevel__Default=Trace